### ISSUE TITLE
Just letting you know the Titled Tuesday repository at my site has changed

### ISSUE THREAD

**Issue by ianrastall** [cmgchess/Titled-Tuesday-Data#59]
Here is the new link. Sorry for it being a OneDrive link:

https://1drv.ms/f/c/91ee28d00abf9121/EpVgfwBI9LhOpkQ86zBjrm0BK3Rtkt7cT3aCiTZi_FEXyw?e=UDuN2h

**Comment by cmgchess** [comment]
@ianrastall Thanks!
updated the readme

**Comment by ianrastall** [comment]
I'm afraid I do need to beg your forgiveness here. I just can't get OneDrive to work as a public repository. I'm in the process of moving everything over to MediaFire, and as such, here is the *actual* link to the files:

https://www.mediafire.com/folder/6ez3624zqt6ot/titled-tuesday

Hope you are well.
