### ISSUE TITLE
scrapers /TitledTuesday.ipynb

### ISSUE THREAD

**Issue by Chessian23** [cmgchess/Titled-Tuesday-Data#7]
for i in range(6):
  r = requests.get(tt+'?&page='+str(i+1))
  soup = BeautifulSoup(r.content, 'html.parser')
  tourn_list = soup.find('table', class_ = 'table-component table-hover table-clickable tournaments-live-table')
  tourn_table_rows = tourn_list.find_all('tr')
  tourn_table_rows = tourn_table_rows[1:]
  for j in tourn_table_rows:
    tourn_link = j.find('a', class_='tournaments-live-name')['href']
    tourn_links.append(tourn_link)

returns this error:

AttributeError                            Traceback (most recent call last)
[z:\Finalized](file:///Z:/Finalized) Scripts\TT Rank Parser.py in line 7
      [117](file:///z%3A/Finalized%20Scripts/TT%20Rank%20Parser.py?line=116) soup = BeautifulSoup(r.content, 'html.parser')
      [118](file:///z%3A/Finalized%20Scripts/TT%20Rank%20Parser.py?line=117) tourn_list = soup.find('table', class_ = 'table-component table-hover table-clickable tournaments-live-table')
----> [119](file:///z%3A/Finalized%20Scripts/TT%20Rank%20Parser.py?line=118) tourn_table_rows = tourn_list.find_all('tr')
      [120](file:///z%3A/Finalized%20Scripts/TT%20Rank%20Parser.py?line=119) tourn_table_rows = tourn_table_rows[1:]
      [121](file:///z%3A/Finalized%20Scripts/TT%20Rank%20Parser.py?line=120) for j in tourn_table_rows:

AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by cmgchess** [comment]
@Chessian23 looks like sometimes the data doesn't load on the page https://www.chess.com/tournament/live/titled-tuesdays?&page=6   
it probably won't break if `for i in range(5):` but it will only fetch the first 5 pages.

anyway I have all the tournament links [here](https://github.com/cmgchess/Titled-Tuesday-Data/tree/main/details)

**Comment by Chessian23** [comment]
> @Chessian23 looks like sometimes the data doesn't load on the page https://www.chess.com/tournament/live/titled-tuesdays?&page=6 it probably won't break if `for i in range(5):` but it will only fetch the first 5 pages.
> 
> anyway I have all the tournament links [here](https://github.com/cmgchess/Titled-Tuesday-Data/tree/main/details)

I love your work and been doing some of my own, but now this is driving me crazy. why would it stop at 5.

**Comment by Chessian23** [comment]
I even tried a delay: time.sleep(3)  # delay to prevent rate limiting

**Comment by cmgchess** [comment]
@Chessian23 still page 6 didn't work? 
just a heads-up
it won't load beyond page 6 anyway. for some reason, it shows the pagination below which is useless tbh

**Comment by Chessian23** [comment]
@cmgchess roger that. kinda frustration but i get it.

**Comment by cmgchess** [comment]
@Chessian23 I managed to get access to all the links starting from 2014. You can maybe scrape them off the md files in the details directory

**Comment by stas-sl** [comment]
Have you tried their API?

Looks like there is a convenient way to get all games (including PGNs) for a single round via API e.g. https://api.chess.com/pub/tournament/early-titled-tuesday-blitz-november-07-2023-4361394/11/1 (you can just open it browser), the only only "inconvenience" is that it seems to work only for round 11, all other rounds return empty results...

**Comment by Chessian23** [comment]
@cmgchess you rock! thank you!!!
